version: "3.9"

services:
#  app:
#    container_name: app
#    build:
#      context: .
#      args:
#        LOCAL: "true"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    links:
#      - db
#    networks:
#      - enrollment

  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=avito