# https://taskfile.dev
version: '3'

silent: true

vars:
  DOCKER_COMPOSE_PATHS: |
    ./deploy/local/docker-compose.yml
    ./deploy/local/docker-compose.swagger-ui.yml
  GO_MODULE: github.com/ninashvl/avito-backend-test
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "*.gen.go" | tr "\n" " "
  GOLANGCI_LINT_VERSION: v1.52.2
  GOLANGCI_LINT_CACHE: .cache/golangci
  DEV_TOOLS: |
    github.com/daixiang0/gci@v0.10.1
    mvdan.cc/gofumpt@v0.4.0
    github.com/deepmap/oapi-codegen/cmd/oapi-codegen@master

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests
      - task: build

  tidy:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    - echo "- Format"
    - gofumpt -l -w {{.GO_FILES}}
    - gci write -s standard -s default -s "prefix({{.GO_MODULE}})" {{.GO_FILES}}

  lint:
    cmds:
      - echo "- Lint"
      - mkdir -p {{.GOLANGCI_LINT_CACHE}}
      - task: lint:cmd
        vars: {CLI_ARGS: "run -v --fix --timeout=5m ./..."}


  lint:cmd:
    cmds:
      - |
        docker run --rm \
          -v "$(pwd):/app" -w /app \
          -v "$(pwd)/{{.GOLANGCI_LINT_CACHE}}:/root/.cache" \
          golangci/golangci-lint:{{.GOLANGCI_LINT_VERSION}} \
          golangci-lint {{.CLI_ARGS}}

  tests:
    cmds:
      - echo "- Tests"
      - go test -race ./...


  build:
    cmds:
      - echo "- Build"
      - go build ./cmd/service


  dev-tools:install:
    cmds:
      - echo "- Install dev tools"
      - |
        {{- range $i, $tool := .DEV_TOOLS | splitLines -}}
          {{ if $tool }} go install -v {{$tool}} {{end}}
        {{end -}}


  gen:api:
    cmds:
      - echo "Generate client server..."
      - oapi-codegen --old-config-style -generate server,types,spec -package v1 ./api/openapi.yaml > ./internal/server/v1/server.gen.go


  generate:
    - echo "Run go generate..."
    - go generate ./...
    - task: gen:api
    - task: fmt

  deps:
    cmds:
      - echo "- Starting deps"
      - task: deps:_cmd
        vars:
          DOCKER_CMD: up -d

  deps:cmd:
    cmds:
      - echo "- Command on deps"
      - task: deps:_cmd
        vars:
          DOCKER_CMD: '{{.CLI_ARGS}}'

  deps:status:
    cmds:
      - echo "- Deps status"
      - task: deps:_cmd
        vars:
          DOCKER_CMD: 'ps -a'

  deps:logs:
    vars:
      DOCKER_CMD:
    cmds:
      - task: deps:_cmd
        vars:
          DOCKER_CMD: 'logs --tail=50 {{.CLI_ARGS}}'

  deps:stop:
    cmds:
      - echo "- Stopping deps"
      - task: deps:_cmd
        vars:
          DOCKER_CMD: 'stop'

  deps:_cmd:
    internal: true
    cmds:
      - echo {{.DOCKER_CMD}}
      - echo "docker compose -f {{ trim .DOCKER_COMPOSE_PATHS | splitLines | join " -f " }} {{.DOCKER_CMD}}"
      - docker compose -f {{ trim .DOCKER_COMPOSE_PATHS | splitLines | join " -f " }} {{.DOCKER_CMD}}