[server]
addr = ":8082"

[database]
host = "db:5432"
user_name = "user"
db_name = "avito"
password = "password"

[s3]
host = "s3:9000"
accessKeyID = "minio-root-user"
secretAccessKey = "minio-root-password"
bucket = "reports"

