version: "3.9"

services:
#  app:
#    container_name: app
#    build:
#      context: .
#      args:
#        LOCAL: "true"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    links:
#      - db
#    networks:
#      - enrollment

  db:
    container_name: db
    ports:
      - "5431:5432"
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=avito
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    container_name: s3
    ports:
      - '9000:9000'
      - '9001:9001'
    image: 'bitnami/minio:latest'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DEFAULT_BUCKETS=reports
